>>> print_sorted = __import__('1-my_list').MyList.print_sorted

SUCCESS CASE:

>>> print_sorted([23, 45, 68])
[23, 45, 68]

>>> print_sorted([-23, -45, -68])
[-68, -45, -23]

>>> print_sorted([-23, 45, -68])
[-68, -23, 45]

>>> print_sorted([-23.3, 45.5, -68.3])
[-68.3, -23.3, 45.5]

>>> print_sorted(['r', 'a', 'u'])
['a', 'r', 'u']

>>> print_sorted([True, False])
[False, True]

>>> print_sorted(['kiwi', 'orange', 'apple'])
['apple', 'kiwi', 'orange']

>>> print_sorted(['kiwi', 'Orange', 'apple'])
['Orange', 'apple', 'kiwi']

>>> print_sorted(['a', 'abc', 'abcd', 'A'])
['A', 'a', 'abc', 'abcd']

>>> print_sorted([(6,4), (1,2), (5,5)])
[(1, 2), (5, 5), (6, 4)]

>>> print_sorted([{(6,4), (1,2), (5,5)}])
[{(1, 2), (6, 4), (5, 5)}]

>>> print_sorted([])
[]

>>> print_sorted([[]])
[[]]

>>> print_sorted([None])
[None]

FAILURE CASES:

>>> print_sorted()
Traceback (most recent call last):
...
TypeError: print_sorted() missing 1 required positional argument: 'self'

>>> print_sorted([23, 45, 68], 7, 4, 9, 2)
Traceback (most recent call last):
...
TypeError: print_sorted() takes 1 positional argument but 5 were given

>>> print_sorted(None)
Traceback (most recent call last):
...
TypeError: 'NoneType' object is not iterable

>>> print_sorted(56, 78, 12)
Traceback (most recent call last):
...
TypeError: print_sorted() takes 1 positional argument but 3 were given

>>> print_sorted([{(6,4), (1,2)}, (5,5)])
Traceback (most recent call last):
...
TypeError: '<' not supported between instances of 'tuple' and 'set'
